"""V0.3a Action contract types."""

from ygo_effect_dsl.engine.action.aggregation import (
    ACTION_AGGREGATION_SCHEMA_VERSION,
    OCGCORE_ACTION_AGGREGATION_EVIDENCE_SCHEMA_VERSION,
    OCGCORE_ACTION_AGGREGATION_METHOD,
    OCGCORE_ACTION_AGGREGATION_SUPPORTED_APIS,
    ActionAggregation,
    ActionAggregationHint,
    ActionAggregationLink,
    ActionDiffOperation,
    ActionDiffTag,
    ActionRole,
    AtomicActionPresentation,
    CompositeActionPresentation,
    DisplaySelection,
    aggregate_replay_events,
    action_aggregation_compatibility_report,
    derive_ocgcore_action_aggregation,
    diff_action_aggregations,
)
from ygo_effect_dsl.engine.action.models import (
    Action,
    ActionKind,
    CardRef,
    EffectRef,
    Selection,
    action_from_dict,
)
from ygo_effect_dsl.engine.action.rollback import (
    ACTIVATION_ROLLBACK_PROBE_SCHEMA_VERSION,
    ACTIVATION_ROLLBACK_SUPPORT_CANDIDATE,
    ACTIVATION_ROLLBACK_UNREACHABLE,
    assert_valid_activation_rollback_probe,
    build_activation_rollback_probe,
)

__all__ = [
    "ACTION_AGGREGATION_SCHEMA_VERSION",
    "ACTIVATION_ROLLBACK_PROBE_SCHEMA_VERSION",
    "ACTIVATION_ROLLBACK_SUPPORT_CANDIDATE",
    "ACTIVATION_ROLLBACK_UNREACHABLE",
    "OCGCORE_ACTION_AGGREGATION_EVIDENCE_SCHEMA_VERSION",
    "OCGCORE_ACTION_AGGREGATION_METHOD",
    "OCGCORE_ACTION_AGGREGATION_SUPPORTED_APIS",
    "Action",
    "ActionAggregation",
    "ActionAggregationHint",
    "ActionAggregationLink",
    "ActionDiffOperation",
    "ActionDiffTag",
    "ActionKind",
    "ActionRole",
    "AtomicActionPresentation",
    "CardRef",
    "CompositeActionPresentation",
    "DisplaySelection",
    "EffectRef",
    "Selection",
    "aggregate_replay_events",
    "action_from_dict",
    "action_aggregation_compatibility_report",
    "assert_valid_activation_rollback_probe",
    "build_activation_rollback_probe",
    "derive_ocgcore_action_aggregation",
    "diff_action_aggregations",
]
